### ISSUE TITLE
Error: unknown JPEG marker 0

### ISSUE THREAD

**Issue by googleoryx** [eugeneware/jpeg-js#81]
Hi guys

I'm getting this error when trying to decode this file. I've attached the file.
![2020-12-07-invalid-jpeg-marker](https://user-images.githubusercontent.com/66191275/101322888-cf4b9480-3878-11eb-9929-ebc7eb4534c4.jpeg)

The stack trace is as follows:
```
Error: unknown JPEG marker 0
    at constructor.parse (SOME_PATH\node_modules\jpeg-js\lib\decoder.js:825:19)
    at Object.decode (SOME_PATH\node_modules\jpeg-js\lib\decoder.js:1096:11)
    at Object.<anonymous> (SOME_PATH\test\download-property.ts:37:6)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Module.m._compile (SOME_PATH\node_modules\ts-node\src\index.ts:493:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Object.require.extensions.<computed> [as .ts] (SOME_PATH\node_modules\ts-node\src\index.ts:496:12)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
```

The jpeg opens fine in:
- Windows 10 Photos
- Microsoft Paint
- Paint.NET
- IE11
- Google Chrome

But I get the following error trying to open the file in Photoshop CS6 (this old version is more sensitive to file issues):
![image](https://user-images.githubusercontent.com/66191275/101323215-5dc01600-3879-11eb-9c1c-3c2c97960359.png)

What do you guys think?

**Comment by patrickhulce** [comment]
Thanks for filing @googleoryx! It looks like a malformed JPEG. Given the current resourcing, this project can't make the same extensive recovery attempts that some other popular decoders can. If it turns out that this a very popular camera and encoder *always* produces files like this (such as the situation in #82), then we'd happily accept a PR for a workaround.

**Comment by NyaomiDEV** [comment]
Hey there! Having the same issue here, but with JPEG music album images. Is there a way of "sanitizing" said images beforehand so that jpeg-js is happy with them?

**Comment by patrickhulce** [comment]
> Is there a way of "sanitizing" said images beforehand so that jpeg-js is happy with them?

Yes, but doing so mostly requires the same level of effort as decoding the JPEG to begin with.

If you are getting images from a popular encoder that _always_ produces files like this, sending examples along with repro steps is the best path to getting a PR for a workaround :)

**Comment by NyaomiDEV** [comment]
> If you are getting images from a popular encoder that _always_ produces files like this, sending examples along with repro steps is the best path to getting a PR for a workaround :)

In my case, I work with unpredictably encoded JPG images, since they're from the Internet itself. Sadly I cannot send a sample and be done with it, as it might just really be corrupted and I wouldn't ever know
